### ISSUE TITLE
error in h5p-hub-client.js

### ISSUE THREAD

**Issue by lesha724** [h5p/h5p-editor-php-library#149]
Hi, I new in h5p and i try integrate h5p in self system, I got this error:
```
h5p-hub-client.js:25 TypeError: Cannot read properties of undefined (reading 'filter')
    at r (h5p-hub-client.js:45:17646)
    at new t (h5p-hub-client.js:40:14273)
    at constructClassInstance (h5p-hub-client.js:25:22216)
    at beginWork (h5p-hub-client.js:25:32954)
    at o (h5p-hub-client.js:25:45116)
    at i (h5p-hub-client.js:25:45436)
    at l (h5p-hub-client.js:25:45674)
    at w (h5p-hub-client.js:25:49014)
    at g (h5p-hub-client.js:25:48742)
    at h (h5p-hub-client.js:25:47981)
```

What could it be? Thanks for the help!

**Comment by ChavezCris** [comment]
Lo pudiste resolver? Porque igual tengo ese error :(
